version: "3.4"

services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: "wagepage"
      POSTGRES_USER: "wagepage"
      POSTGRES_PASSWORD: "wagepage"
    ports:
      - "5432:5432"